// The 3D table's Material 3 colours, generated from one seed colour with
// Google's Material Color Utilities (docs/TABLE3D.md section 8.4).
//
//   node_modules/.bin/esbuild tools/scheme.mjs --bundle --platform=node \
//     --format=esm --log-level=error | node --input-type=module
//
// (Bundled first: the library imports its own files without extensions,
// which Node's ES modules refuse.) It prints the CSS custom properties that
// web3d/src/style.css carries, between its "generated" markers; paste them
// there. The library is used here, at build time, and never ships.

import {
  argbFromHex,
  customColor,
  hexFromArgb,
  Hct,
  MaterialDynamicColors,
  SchemeTonalSpot,
} from "@material/material-color-utilities";

// A clear blue: the card back is navy and white, and the table a pale sky.
const SEED = "#2f5da8";
// The two sides, as the score tab shows them: a warm amber for you and a teal
// for your opponent, each pulled a little towards the seed so they belong.
const SIDES = [
  ["you", "#e39a2d"],
  ["them", "#1f9e93"],
];

const ROLES = [
  "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
  "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
  "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
  "error", "onError", "errorContainer", "onErrorContainer",
  "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
  "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
  "surfaceContainerHigh", "surfaceContainerHighest", "surfaceDim", "surfaceBright",
  "outline", "outlineVariant", "inverseSurface", "inverseOnSurface", "inversePrimary",
  "shadow", "scrim", "surfaceTint",
];

const kebab = (s) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), false, 0);
const lines = ROLES.map((role) => `  --md-sys-color-${kebab(role)}: ${hexFromArgb(MaterialDynamicColors[role].getArgb(scheme))};`);
for (const [name, hex] of SIDES) {
  const { light } = customColor(argbFromHex(SEED), { name, value: argbFromHex(hex), blend: true });
  lines.push(
    `  --piquet-${name}: ${hexFromArgb(light.color)};`,
    `  --piquet-on-${name}: ${hexFromArgb(light.onColor)};`,
    `  --piquet-${name}-container: ${hexFromArgb(light.colorContainer)};`,
    `  --piquet-on-${name}-container: ${hexFromArgb(light.onColorContainer)};`,
  );
}
console.log(`  /* generated by web3d/tools/scheme.mjs from seed ${SEED} */\n${lines.join("\n")}\n  /* end generated */`);
